import "./globals.css";
import { AuthProvider } from "@/context/AuthContext";
import { Toaster } from "sonner"

export const metadata = {
  title: "Task Manager Solve",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
    return (
        <html lang="pt-BR">
            <body
                className={`antialiased`}
            >
                <AuthProvider>
                    {children}
                    <Toaster />
                </AuthProvider>
            </body>
        </html>
    );
}
